services:
  - type: web
    name: manish-csc-center
    runtime: go
    rootDir: backend
    buildCommand: go build -o server .
    startCommand: ./server
    envVars:
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
