services:
  - type: web
    name: manish-csc-center
    runtime: go
    buildCommand: cd backend && go build -o server .
    startCommand: cd backend && ./server
    envVars:
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
